package com.android.lixiang.cheshang.presenter.data.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.lixiang.cheshang.presenter.data.greenDao.Answer;
import com.android.lixiang.cheshang.presenter.data.greenDao.Msg;
import com.android.lixiang.cheshang.presenter.data.greenDao.User;
import com.android.lixiang.cheshang.presenter.data.greenDao.Record;

import com.android.lixiang.cheshang.presenter.data.greenDao.AnswerDao;
import com.android.lixiang.cheshang.presenter.data.greenDao.MsgDao;
import com.android.lixiang.cheshang.presenter.data.greenDao.UserDao;
import com.android.lixiang.cheshang.presenter.data.greenDao.RecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig answerDaoConfig;
    private final DaoConfig msgDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig recordDaoConfig;

    private final AnswerDao answerDao;
    private final MsgDao msgDao;
    private final UserDao userDao;
    private final RecordDao recordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        answerDaoConfig = daoConfigMap.get(AnswerDao.class).clone();
        answerDaoConfig.initIdentityScope(type);

        msgDaoConfig = daoConfigMap.get(MsgDao.class).clone();
        msgDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        answerDao = new AnswerDao(answerDaoConfig, this);
        msgDao = new MsgDao(msgDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        recordDao = new RecordDao(recordDaoConfig, this);

        registerDao(Answer.class, answerDao);
        registerDao(Msg.class, msgDao);
        registerDao(User.class, userDao);
        registerDao(Record.class, recordDao);
    }
    
    public void clear() {
        answerDaoConfig.clearIdentityScope();
        msgDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        recordDaoConfig.clearIdentityScope();
    }

    public AnswerDao getAnswerDao() {
        return answerDao;
    }

    public MsgDao getMsgDao() {
        return msgDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

}
